theme: jekyll-theme-slate
lang: ja-JP
title: '<a href="/ShellGeiData/" style="color:white">シェル芸の情報を集めるサイト</a>'
description: <a href="https://shellgei.github.io/info/">ここ</a>に移転しました。
markdown: kramdown
highlighter: rouge
